---
# Shrink default replicas.
replicas: 1

# Disable sysctl.
sysctlInitContainer:
  enabled: false

# Shrink default JVM heap.
esJavaOpts: "-Xms512m -Xmx512m"

# Allocate smaller chunks of memory per pod.
resources:
  limits:
    cpu: 300m
    memory: 1Gi
  requests:
    cpu: "100m"
    memory: "512M"

# Request smaller persistent volumes.
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "standard"
  resources:
    requests:
      storage: 1Gi
